stages:
    - test
    - build

test_develop:
    stage: test
    image: gitlab.orr.noaa.gov:5002/centos-conda
    script:
        - cp platform/centos/mongodb-org-4.2.repo /etc/yum.repos.d
        - yum install mongodb-org -y
        - ls -l /etc/mongod.conf
        - more /etc/mongod.conf
        - ls -l /var/log/mongodb/
        - ls -l /var/lib/mongo
  
        - mongod --config /etc/mongod.conf &

        - cd oil_db
        - pwd
        - conda install --file conda_requirements.txt
        - pip install -r pip_requirements.txt
        - python setup.py develop
        
        - yes | oil_db_init
        - oil_db_import --all

        - pytest oil_database
    tags:
        - docker

build:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oil-database
        - docker push gitlab.orr.noaa.gov:5002/oil-database
    tags:
        - shell
        - build
        