stages:
    - test
    - build1
    - build2

test_develop:
    stage: test
    image: registry.orr.noaa.gov/erd/centos-conda

    script:
        # Install & test the oil_library package
        - echo "ip_resolve=4" >> /etc/yum.conf
        - yum update -y

        # mongo should have been installed by conda, but conda doesn't reserve
        # places for the logs, the database, and the pidfile
        - mkdir /var/lib/mongo
        - mkdir /var/log/mongodb
        - mkdir /var/run/mongodb

        - mongod --config mongo_config_dev.yml &

        - conda install -y requests lxml

        - cd adios_db
        - conda install -y --file conda_requirements.txt
        - pip install -e ./


        - cd data/exxon_assays
        - python ./download_exxon_assays.py
        - cd -

        - adios_db_init
        - adios_db_import --all

        - pytest --mongo adios_db

        # Install & test the oil_library_api package
        - cd ../web_api
        - conda install -y --file conda_requirements.txt
        - pip install -e ./

        - pytest adios_db_api
    tags:
        - docker

build_api:
    stage: build1

    script:
        # URI format: <hostname>/<group>/<subgroup>/<project>/<module-name>
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_api/dockerfile . -t registry.orr.noaa.gov/gnome/oil_database/oil_database/api
        - docker push registry.orr.noaa.gov/gnome/oil_database/oil_database/api
    tags:
        - shell
        - build

build_client:
    stage: build2

    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_client/dockerfile . -t registry.orr.noaa.gov/gnome/oil_database/oil_database/client
        - docker push registry.orr.noaa.gov/gnome/oil_database/oil_database/client
    tags:
        - shell
        - build
