stages:
    - test
    - build

test_develop:
    stage: test
    image: gitlab.orr.noaa.gov:5002/centos-conda
    script:
        # Install & test the oil_library package
        - cp platform/centos/mongodb-org-4.2.repo /etc/yum.repos.d
        - yum install mongodb-org -y
        - mongod --config /etc/mongod.conf &

        - cd oil_db
        - conda install --file conda_requirements.txt
        - pip3 install -r pip_requirements.txt
        - python setup.py develop
        
        - oil_db_init
        - oil_db_import --all

        - pytest oil_database

        # Install & test the oil_library_api package
        - cd ../web_api
        - conda install --file conda_requirements.txt
        - pip3 install -r pip_requirements.txt
        - python setup.py develop

        - pytest oil_database_api
    tags:
        - docker

build:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oil-database
        - docker push gitlab.orr.noaa.gov:5002/oil-database
    tags:
        - shell
        - build
        