stages:
    - test
    - build1
    - build2

test_develop:
    stage: test
    image: registry.orr.noaa.gov/erd/centos-conda

    script:
        # Install & test the oil_library package
        - echo "ip_resolve=4" >> /etc/yum.conf
        - cp platform/centos/mongodb-org-4.2.repo /etc/yum.repos.d
        - yum install mongodb-org -y
        - mongod --config /etc/mongod.conf &

        - cd oil_db
        - conda install --file conda_requirements.txt
        - pip install -r pip_requirements.txt
        - python setup.py develop

        - cd data/exxon_assays
        - python ./download_exxon_assays.py
        - cd -

        - oil_db_init
        - oil_db_import --all

        - pytest oil_database

        # Install & test the oil_library_api package
        - cd ../web_api
        - conda install --file conda_requirements.txt
        - pip install -r pip_requirements.txt
        - python setup.py develop

        - pytest oil_database_api
    tags:
        - docker

build_api:
    stage: build1
    image: registry.orr.noaa.gov/erd/centos-conda

    script:
        - echo "ip_resolve=4" >> /etc/yum.conf
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_api/dockerfile . -t registry.orr.noaa.gov/gnome/oil_database/oil_database/api
        - docker push registry.orr.noaa.gov/gnome/oil_database/oil_database/api
    tags:
        - shell
        - build

build_client:
    stage: build2
    image: registry.orr.noaa.gov/erd/centos-conda

    script:
        - echo "ip_resolve=4" >> /etc/yum.conf
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_client/dockerfile . -t registry.orr.noaa.gov/gnome/oil_database/oil_database/client
        - docker push registry.orr.noaa.gov/gnome/oil_database/oil_database/client
    tags:
        - shell
        - build
