variables:
  PYTHON_VER: '3.11'
  CI_APPLICATION_TAG: $CI_COMMIT_SHA-api-stage
  TF_DESTROY: 'false'
  MY_SERVER_ROLE_TAG: 'adios'
  TRAEFIK_IMAGE: '$SYSADMIN_CONTAINER_REGISTRY/sidecar-traefik/sidecar-traefik:1.1.2'

include:
  - component: $CI_SERVER_FQDN/components/build-publish-docker-image/BuildPublishContainerRegistryImage@v3.0.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Do not run this job for merge requests
        when: never
      - if: $CI_PIPELINE_SOURCE == "pipeline" # Do not run this job for pipelines
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Build ADIOS API Image' # (Optional) The name of the GitLab job. If not specified then `BuildDockerImage` is used.
      stage: build # Specifies the pipeline stage (e.g., build, test, deploy) where the component will run
      build-args: # (Optional) Docker build arguments passed to the Dockerfile during the build
        - PYTHON_VER=$PYTHON_VER # Python version to be used in the Docker image.
        - noaa_oil_data_token=$noaa_oil_data_token
      version: $CI_COMMIT_REF_NAME # (Optional) Specifies the image version, following semantic versioning. If the version is not specified, then `0.0.0-build.${CI_COMMIT_SHORT_SHA}` is used.
      image-name: 'adios-api' # The name of the Docker image to be built and published. The CI_REGISTRY_IMAGE path is added through the job.
      dockerfile-path: ./web_api/dockerfile # Relative path to the Dockerfile in your repository. Useful if your Dockerfile is in a non-standard location.
      latest: true
  - component: $CI_SERVER_FQDN/components/build-publish-docker-image/BuildPublishContainerRegistryImage@v3.0.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Do not run this job for merge requests
        when: never
      - if: $CI_PIPELINE_SOURCE == "pipeline" # Do not run this job for pipelines
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Build Production ADIOS API Image' # (Optional) The name of the GitLab job. If not specified then `BuildDockerImage` is used.
      stage: build # Specifies the pipeline stage (e.g., build, test, deploy) where the component will run
      build-args: # (Optional) Docker build arguments passed to the Dockerfile during the build
        - PYTHON_VER=$PYTHON_VER # Python version to be used in the Docker image.
        - noaa_oil_data_token=$noaa_oil_data_token
        - BRANCH_NAME=production
      version: $CI_COMMIT_REF_NAME # (Optional) Specifies the image version, following semantic versioning. If the version is not specified, then `0.0.0-build.${CI_COMMIT_SHORT_SHA}` is used.
      image-name: 'adios-api-public' # The name of the Docker image to be built and published. The CI_REGISTRY_IMAGE path is added through the job.
      dockerfile-path: ./web_api/dockerfile # Relative path to the Dockerfile in your repository. Useful if your Dockerfile is in a non-standard location.
      latest: true
  - component: $CI_SERVER_FQDN/components/build-publish-docker-image/BuildPublishContainerRegistryImage@v3.0.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Do not run this job for merge requests
        when: never
      - if: $CI_PIPELINE_SOURCE == "pipeline" # Do not run this job for pipelines
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Build debug ADIOS client Image' # (Optional) The name of the GitLab job. If not specified then `BuildDockerImage` is used.
      stage: build # Specifies the pipeline stage (e.g., build, test, deploy) where the component will run
      version: $CI_COMMIT_REF_NAME # (Optional) Specifies the image version, following semantic versioning. If the version is not specified, then `0.0.0-build.${CI_COMMIT_SHORT_SHA}` is used.
      image-name: 'adios-client-debug' # The name of the Docker image to be built and published. The CI_REGISTRY_IMAGE path is added through the job.
      dockerfile-path: ./web_client/dockerfile # Relative path to the Dockerfile in your repository. Useful if your Dockerfile is in a non-standard location.
      latest: true
  - component: $CI_SERVER_FQDN/components/build-publish-docker-image/BuildPublishContainerRegistryImage@v3.0.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Do not run this job for merge requests
        when: never
      - if: $CI_PIPELINE_SOURCE == "pipeline" # Do not run this job for pipelines
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Build ADIOS client Image' # (Optional) The name of the GitLab job. If not specified then `BuildDockerImage` is used.
      stage: build # Specifies the pipeline stage (e.g., build, test, deploy) where the component will run
      version: $CI_COMMIT_REF_NAME # (Optional) Specifies the image version, following semantic versioning. If the version is not specified, then `0.0.0-build.${CI_COMMIT_SHORT_SHA}` is used.
      image-name: 'adios-client' # The name of the Docker image to be built and published. The CI_REGISTRY_IMAGE path is added through the job.
      dockerfile-path: ./web_client/dockerfile # Relative path to the Dockerfile in your repository. Useful if your Dockerfile is in a non-standard location.
      build-args:
        - BUILD_ENV=production
      latest: true
  - component: $CI_SERVER_FQDN/components/docker-compose/DockerCompose@v1.0.5
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Deploy Dev'
      action: 'deploy'
      server-role-tag: $MY_SERVER_ROLE_TAG
      docker-compose-file-path: './docker/docker-compose.yml'
      environment-name: 'dev'
      log-level: 'debug'
      deployment-target: 'vmware'
      docker-compose-pull-images: true
      docker-compose-environment-variables:
        - SIDECAR_TRAEFIK_IMAGE=$TRAEFIK_IMAGE
        - CLIENT_IMAGE=$CI_REGISTRY_IMAGE/adios-client-debug:$CI_COMMIT_REF_NAME
        - API_IMAGE=$CI_REGISTRY_IMAGE/adios-api:$CI_COMMIT_REF_NAME
        - AUTH_COOKIE_SECRET=$AUTH_COOKIE_SECRET
        - AUTH_SECRET=$AUTH_SECRET
        - AUTH_URL='https://sso.orr.noaa.gov/realms/ORR'
        - AUTH_CLIENT_ID='adios'
        - PUBLIC_ACCESS_PATH='/' # '/' allows public access to the whole application '/nullpath/' restricts public access to everything except the /nullpath/ endpoint.
        - CAN_MODIFY_DB=true # Set to true to allow the API to modify the database. Set to false to restrict the API to read-only operations. Defaults to false.
  - component: $CI_SERVER_FQDN/components/docker-compose/DockerCompose@v1.0.5
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Deploy Production (editable)'
      action: 'deploy'
      server-role-tag: $MY_SERVER_ROLE_TAG
      docker-compose-file-path: './docker/docker-compose.yml'
      environment-name: 'prod'
      log-level: 'debug'
      deployment-target: 'aws'
      docker-compose-pull-images: true
      docker-compose-environment-variables:
        - SIDECAR_TRAEFIK_IMAGE=$TRAEFIK_IMAGE
        - CLIENT_IMAGE=$CI_REGISTRY_IMAGE/adios-client:$CI_COMMIT_REF_NAME
        - API_IMAGE=$CI_REGISTRY_IMAGE/adios-api:$CI_COMMIT_REF_NAME
        - AUTH_COOKIE_SECRET=$AUTH_COOKIE_SECRET
        - AUTH_SECRET=$AUTH_SECRET
        - AUTH_URL='https://sso.orr.noaa.gov/realms/ORR'
        - AUTH_CLIENT_ID='adios'
        - PUBLIC_ACCESS_PATH='/nullpath/' # '/' allows public access to the whole application '/nullpath/' restricts public access to everything except the /nullpath/ endpoint.
        - CAN_MODIFY_DB=true # Set to true to allow the API to modify the database. Set to false to restrict the API to read-only operations. Defaults to false.
  - component: $CI_SERVER_FQDN/components/docker-compose/DockerCompose@v1.0.5
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Deploy Public'
      action: 'deploy'
      server-role-tag: $MY_SERVER_ROLE_TAG
      docker-compose-file-path: './docker/docker-compose.yml'
      environment-name: 'prod'
      log-level: 'debug'
      deployment-target: 'aws'
      docker-compose-pull-images: true
      docker-compose-environment-variables:
        - SIDECAR_TRAEFIK_IMAGE=$TRAEFIK_IMAGE
        - CLIENT_IMAGE=$CI_REGISTRY_IMAGE/adios-client:$CI_COMMIT_REF_NAME
        - API_IMAGE=$CI_REGISTRY_IMAGE/adios-api-public:$CI_COMMIT_REF_NAME
        - AUTH_COOKIE_SECRET=$AUTH_COOKIE_SECRET
        - AUTH_SECRET=$AUTH_SECRET
        - AUTH_URL='https://sso.orr.noaa.gov/realms/ORR'
        - AUTH_CLIENT_ID='adios'
        - PUBLIC_ACCESS_PATH='/' # '/' allows public access to the whole application '/nullpath/' restricts public access to everything except the /nullpath/ endpoint.
        - CAN_MODIFY_DB=false # Set to true to allow the API to modify the database. Set to false to restrict the API to read-only operations. Defaults to false.a
  - component: $CI_SERVER_FQDN/components/ansible/Ansible@v1.3.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Sync with under review'
      stage: maintenance
      log-level: info
      when: manual
      environment-name: 'dev'
      deployment-target: 'vmware'
      playbook-file-name: 'sync-with-under-review.yml'
      ansible-inventory-file: hosts/vmware.yml
      runner-tags:
        - ansible-playbooks
        - Infrastructure
        - developer-ci-templates
  - component: $CI_SERVER_FQDN/components/ansible/Ansible@v1.3.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Load mongodb with data from repository'
      stage: maintenance
      log-level: info
      when: manual
      environment-name: 'dev'
      deployment-target: 'vmware'
      playbook-file-name: 'load-data-from-repo.yml'
      ansible-inventory-file: hosts/vmware.yml
      runner-tags:
        - ansible-playbooks
        - Infrastructure
        - developer-ci-templates
  - component: $CI_SERVER_FQDN/components/ansible/Ansible@v1.3.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Sync with production'
      stage: maintenance
      log-level: info
      when: manual
      environment-name: 'dev'
      deployment-target: 'vmware'
      playbook-file-name: 'sync-with-production.yml'
      ansible-inventory-file: hosts/vmware.yml
      runner-tags:
        - ansible-playbooks
        - Infrastructure
        - developer-ci-templates
  - component: $CI_SERVER_FQDN/components/ansible/Ansible@v1.3.0
    rules:
      - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
        when: never
      - if: $CI_COMMIT_REF_NAME
    inputs:
      job-name: 'Pull remote under review'
      stage: maintenance
      log-level: info
      when: manual
      environment-name: 'dev'
      deployment-target: 'vmware'
      playbook-file-name: 'sync-with-production.yml'
      ansible-inventory-file: hosts/vmware.yml
      runner-tags:
        - ansible-playbooks
        - Infrastructure
        - developer-ci-templates

stages:
  - pre-test
  - build
  - verify
  - deploy_db
  - deploy
  - test
  - maintenance

test_develop:
  stage: pre-test
  image: registry.orr.noaa.gov/erd/environments/ubuntu/ubuntuforge-python$PYTHON_VER
  #  image: registry.orr.noaa.gov/erd/centos-conda/ubuntu/ubuntuforge-python$PYTHON_VER
  tags:
    - docker
    - linux

  rules:
    - if: $TF_DESTROY == "true" # Do not run when TF_DESTROY is true
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME
      when: always
  before_script:
    - apt update
    - apt upgrade -y

    # mongod fails if the tzdata package is missing
    - echo 'tzdata tzdata/Areas select America' | debconf-set-selections
    - echo 'tzdata tzdata/Zones/America select Los_Angeles' |
      debconf-set-selections
    - DEBIAN_FRONTEND="noninteractive" apt install -y tzdata

  script:
    # install all the requirements
    - >
      conda install -y python=$PYTHON_VER --file adios_db/conda_requirements.txt
      --file adios_db/conda_requirements_optional.txt --file
      adios_db/conda_requirements_test.txt --file web_api/conda_requirements.txt

    # configure and start mongodb

    # mongo should have been installed by conda, but conda doesn't reserve
    # places for the logs, the database, and the pidfile
    # note: maybe we should update the test config so we don't need this??
    #       and then we could save the logs, etc as an artifact as well.
    - mkdir /var/lib/mongo
    - mkdir /var/log/mongodb
    - mkdir /var/run/mongodb

    # We can start the docker container manually like this:
    #   docker run --volume $(pwd)/git_repos/oil_database:/oil_database -it registry.orr.noaa.gov/erd/environments/ubuntu/ubuntuforge-python3.11 /bin/bash

    - mongod --config mongo_config_test.yml &

    # apt-get install -y lsof
    # lsof -nP -iTCP -sTCP:LISTEN  # see if mongod is listening

    # Install & test the adios_db package
    - cd adios_db
    - pip install ./
    - pytest --mongo --import adios_db/test

    # Install & test the adios_db_api package
    - cd ../web_api
    - pip install ./
    - pytest adios_db_api/tests

Build Dev Server:
  stage: build
  needs: []
  variables:
    # Basic metadata for Terraform.
    TF_VAR_line_office: NOS
    TF_VAR_division: ERD
    TF_VAR_program: ORR
    TF_VAR_program_manager: 'amy.macfadyen@noaa.gov'
    TF_VAR_system_owner_name: 'James Makela'
    TF_VAR_system_owner_email: 'james.makela@noaa.gov'
    TF_VAR_vm_template_name: $GLOBAL_REDHAT_BASELINE_STABLE
    TF_VAR_role_tag: '$MY_SERVER_ROLE_TAG'
    TF_STATE_NAME: 'Development' # (LEAVE ME)
    TF_VAR_environment_tag: 'Development' # (LEAVE ME) Case-sensitive; indicates where your server deploys.
    TF_VAR_application_name: 'adios-dev' # (CHANGE ME) Used as a tag and part of the server name. Include -dev as a suffix.
    TF_VAR_instance_count: 1 # (LEAVE ME) Usually 1 unless a system admin instructs otherwise.
    TF_VAR_vm_data_disk_size: 100 # (LEAVE or CHANGE ME) The "data" disk for Docker volumes and data.
    TF_VAR_vm_disk_size: 100 # (LEAVE ME) The root volume size, typically enough for most uses.
    TF_ROOT: 'terraform/vmware' # (LEAVE ME) Points Terraform to the correct directory.
    TF_VAR_vm_cpu_cores_per_socket: 1 # (LEAVE or CHANGE ME) CPU cores per socket.
    TF_VAR_vm_cpu_cores: 6 # (LEAVE or CHANGE ME) Total CPU sockets.
    TF_VAR_vm_memory: 8192 # (LEAVE or CHANGE ME) Amount of RAM. Typically 2GB or 4GB is enough.

  trigger:
    forward:
      pipeline_variables: true
    strategy: depend # (LEAVE ME)
    include:
      - project: templates/developer-ci-templates # (LEAVE ME)
        ref: latest # (LEAVE ME)
        file: 'jobs/terraform/terraform.vm.gitlab-ci.yml' # (LEAVE ME)

Build Production Server:
  stage: build
  needs: []
  variables:
    # Basic metadata for Terraform.
    TF_VAR_line_office: NOS
    TF_VAR_division: ERD
    TF_VAR_program: ORR
    TF_VAR_program_manager: 'amy.macfadyen@noaa.gov'
    TF_VAR_system_owner_name: 'James Makela'
    TF_VAR_system_owner_email: 'james.makela@noaa.gov'
    TF_VAR_vm_template_name: $GLOBAL_REDHAT_BASELINE_STABLE
    TF_VAR_role_tag: '$MY_SERVER_ROLE_TAG'
    TF_VAR_environment_tag: 'prod' # (LEAVE ME) Case-sensitive; indicates where your server deploys.
    TF_VAR_application_name: 'adios-prod' # (CHANGE ME) Used as a tag and part of the server name. Include -dev as a suffix.
    TF_VAR_instance_count: 1 # (LEAVE ME) Usually 1 unless a system admin instructs otherwise.
    TF_VAR_ami_name: '$GLOBAL_LATEST_RHEL8_BASELINE'
    TF_STATE_NAME: 'prod'
    TF_ROOT: 'terraform/aws'
    TF_VAR_account_tag: 'erma'
    TF_VAR_instance_type: 't3.small' # Please dont use a t3.micro
    TF_VAR_root_volume_type: 'gp2'
    TF_VAR_root_volume_size: 100
    TF_VAR_data_volume_type: 'gp2'
    TF_VAR_data_volume_size: 100
    TF_VAR_subnet_id: 'subnet-041022ffbcb0cd6e8'
    TF_VAR_security_group_id: 'sg-0cfd1c6f73bc2f1e5'
  trigger:
    forward:
      pipeline_variables: true
    strategy: depend
    include:
      - project: templates/developer-ci-templates
        ref: develop
        file: jobs/terraform/terraform.ec2.gitlab-ci.yml

Build Public Server:
  stage: build
  needs: []
  variables:
    # Basic metadata for Terraform.
    TF_VAR_line_office: NOS
    TF_VAR_division: ERD
    TF_VAR_program: ORR
    TF_VAR_program_manager: 'amy.macfadyen@noaa.gov'
    TF_VAR_system_owner_name: 'James Makela'
    TF_VAR_system_owner_email: 'james.makela@noaa.gov'
    TF_VAR_vm_template_name: $GLOBAL_REDHAT_BASELINE_STABLE
    TF_VAR_role_tag: '$MY_SERVER_ROLE_TAG'
    TF_VAR_environment_tag: 'prod' # (LEAVE ME) Case-sensitive; indicates where your server deploys.
    TF_VAR_application_name: 'adios-pub' # (CHANGE ME) Used as a tag and part of the server name. Include -dev as a suffix.
    TF_VAR_instance_count: 1 # (LEAVE ME) Usually 1 unless a system admin instructs otherwise.
    TF_VAR_ami_name: '$GLOBAL_LATEST_RHEL8_BASELINE'
    TF_STATE_NAME: 'public'
    TF_ROOT: 'terraform/aws'
    TF_VAR_account_tag: 'erma'
    TF_VAR_instance_type: 't3.small' # Please dont use a t3.micro
    TF_VAR_root_volume_type: 'gp2'
    TF_VAR_root_volume_size: 100
    TF_VAR_data_volume_type: 'gp2'
    TF_VAR_data_volume_size: 100
    TF_VAR_subnet_id: 'subnet-041022ffbcb0cd6e8'
    TF_VAR_security_group_id: 'sg-0cfd1c6f73bc2f1e5'
  trigger:
    forward:
      pipeline_variables: true
    strategy: depend
    include:
      - project: templates/developer-ci-templates
        ref: develop
        file: jobs/terraform/terraform.ec2.gitlab-ci.yml

.drop_db_volume_public:
  stage: maintenance
  image: registry.orr.noaa.gov/erd/environments/ubuntu/ubuntuforge-python$PYTHON_VER
  when: manual
  environment:
    name: public
    url: https://adios.orr.noaa.gov
  tags:
    - adios-prod
  variables:
    DB_VOLUME: dbdata
  script:
    - docker volume rm $DB_VOLUME
