stages:
    - test
    - build1
    - build2

test_develop:
    stage: test
    image: registry.orr.noaa.gov/erd/centos-conda

    script:
        # Install & test the oil_library package
        - cd adios_db
        - conda install -y --file conda_requirements.txt
        - pip install -e ./

        # mongo should have been installed by conda
        # - cp platform/centos/mongodb-org-4.2.repo /etc/yum.repos.d
        # - yum install mongodb-org -y
        - cd ..
        - mongod --config mongo_config_dev.yml &

        # - cd data/exxon_assays
        # - python ./download_exxon_assays.py
        # - cd -

        - adios_db_init
        - adios_db_import --all

        - pytest --mongo adios_db/adios_db

        # Install & test the oil_library_api package
        - cd web_api
        - conda install -y --file conda_requirements.txt
        - pip install -e ./

        - pytest adios_db_api
    tags:
        - docker

build_api:
    stage: build1
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_api/dockerfile . -t registry.orr.noaa.gov/gnome/adios_db/adios_db/api
        - docker push registry.orr.noaa.gov/gnome/adios_db/adios_db/api
    tags:
        - shell
        - build

build_client:
    stage: build2
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f web_client/dockerfile . -t registry.orr.noaa.gov/gnome/adios_db/adios_db/client
        - docker push registry.orr.noaa.gov/gnome/adios_db/adios_db/client
    tags:
        - shell
        - build
