stages:
    - test
    - build

test_develop:
    stage: test
    image: gitlab.orr.noaa.gov:5002/centos-conda
    script:
        - cd oil_db
        - pwd
        - conda install --file conda_requirements.txt
        - pip install -r pip_requirements.txt
        - python setup.py develop
        
        - yes | oil_db_init
        - oil_db_import --all

        - pytest oil_database
    tags:
        - docker

build:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oil-database
        - docker push gitlab.orr.noaa.gov:5002/oil-database
    tags:
        - shell
        - build
        