# configuration for mongodb

net:
  bindIp: 127.0.0.1  # Enter 0.0.0.0,:: to bind to all IPv4 and IPv6 addresses or, alternatively, use the net.bindIpAll setting.
  port: 27017  # this is the mongo default

storage:
   dbPath: "<path_to_project>/mongo_files"
   journal:
     enabled: true

systemLog:
  destination: file
  logAppend: true
  path: "<path_to_project>/mongo_files/mongod.log"

processManagement:
  fork: false
  pidFilePath: "<path_to_project>/mongo_files/mongod.pid"  # location of pidfile
  timeZoneInfo: "/usr/share/zoneinfo"
