# configuration for mongodb

net:
  port: 27017  # this is the mongo default
  wireObjectCheck : false
  unixDomainSocket: 
      enabled : true

storage:
  engine: wiredTiger
  dbPath: mongo_files
  directoryPerDB: true
  journal:
      enabled: true

systemLog:
  destination: file
  path: "/var/log/mongodb/mongod.log"
  logAppend: true
  timeStampFormat: iso8601-utc

processManagement:
  fork: true
