"""
Main class that represents an oil record.

This maps to the JSON used in the DB

Having a Python class makes it easier to write importing, validating etc, code.
"""
from dataclasses import dataclass, field

from ..common.utilities import dataclass_to_json

from .values import ProductType, Reference
from .sample import SampleList


@dataclass_to_json
@dataclass
class Oil:
    name: str  # only required field
    _id: str = ""
    oil_id: str = ""

    status: list = field(default_factory=list)
    extra_data: dict = field(default_factory=dict)
    sub_samples: SampleList = field(default_factory=SampleList)

    # meta data
    location: str = ""
    reference: Reference = None
    sample_date: str = ""
    comments: str = ""
    API: float = None
    product_type: ProductType = ""
    labels: list = field(default_factory=list)

    def __post_init__(self):
        """
        put any validation code here (__init__ is auto-generated by dataclass)

        right now, a non-empty name is it.
        """
        if self.name == "":
            raise TypeError("Name must be a non-empty string")
