# Oil Database Web Client production Docker configuration
#
FROM registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9

RUN echo "ip_resolve=4" >> /etc/yum.conf

RUN yum -y update
RUN yum -y install nodejs
RUN yum -y install npm
RUN yum -y install nginx

COPY ./web_client/ /web_client/
COPY ./oildb-deploy/config/public/web_client/ /config/

WORKDIR web_client

#
# build our production web client
#
RUN npm install -g n
RUN n 14
RUN node --version

RUN npm install npm@latest -g
RUN npm install
RUN npm --version

RUN npm install -g ember-cli

RUN ember build --environment production

#
# copy our configs to the built distribution & nginx
#
RUN cp /config/main.json dist/configs

#
# put our distribution in its own area
#
RUN cp -r dist /adios_client
RUN chgrp -R nginx /adios_client/*
RUN chmod 640 /adios_client/configs/*
RUN chmod 644 /adios_client/assets/images/*

#
# clean up
#
WORKDIR /
RUN rm -rf /web_client

ENTRYPOINT ["/usr/sbin/nginx", "-c", "/config/nginx.conf", "-g", "daemon off;"]
