# Oil Database Web Client Docker configuration
#

FROM gitlab.orr.noaa.gov:5002/centos-conda

RUN yum update -y && yum -y install node npm

COPY ./web_client/ /web_client/

RUN mkdir /config
RUN cp /web_client/config-example.json /config/config.json
RUN ln -s /config/config.json /web_client/public/assets/config.json
RUN cd /web_client && npm install 

VOLUME /config
EXPOSE 4200
ENTRYPOINT ["/webgnomeclient/docker_start.sh"]
