# Oil Database Web Client production Docker configuration
#
#FROM registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9
FROM node:18.18.2-buster

#RUN yum -y install nginx
RUN apk update
RUN apk add nginx


COPY ./web_client/ /web_client/
COPY ./oildb-deploy/config/public/web_client/ /config/

WORKDIR web_client

RUN npm install npm@latest -g
RUN node --version
RUN npm --version

# ember-cli should already be in our package.json, but we want to install it globally.
RUN npm install ember-cli -g
RUN ember --version
RUN node --version
RUN npm --version

RUN ember build --environment production

#
# copy our configs to the built distribution & nginx
#
RUN cp /config/main.json dist/configs

#
# put our distribution in its own area
#
RUN cp -r dist /adios_client
RUN chgrp -R nginx /adios_client/*
RUN chmod 640 /adios_client/configs/*
RUN chmod 644 /adios_client/assets/images/*

#
# clean up
#
WORKDIR /
RUN rm -rf /web_client

ENTRYPOINT ["/usr/sbin/nginx", "-c", "/config/nginx.conf", "-g", "daemon off;"]
