# Oil Database Web Client production Docker configuration
#
FROM registry.orr.noaa.gov/erd/centos-conda

RUN yum update -y && yum -y install node npm nginx

COPY ./web_client/ /web_client/
COPY ./oildb-deploy/config/web_client/ /config/

WORKDIR web_client

RUN npm install -g n
RUN n stable
RUN node --version

RUN npm install npm@latest -g
RUN npm install
RUN npm --version

RUN npm install -g ember-cli

RUN ember build --environment production

RUN cp -r --remove-destination dist/* /usr/share/nginx/html/

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
