# Oil Database Web Client Docker configuration
#
#FROM registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9
FROM node:18.18.2-buster-slim

RUN echo "ip_resolve=4" >> /etc/yum.conf

RUN yum -y update

COPY ./web_client/ /web_client/
COPY ./oildb-deploy/config/stage/web_client/ /web_client/public/configs/

RUN npm install npm@latest -g
RUN npm --version

# ember-cli should already be in our package.json, but we want to install it globally.
RUN npm install ember-cli -g
RUN ember --version

RUN cd /web_client && npm install

EXPOSE 4200
ENTRYPOINT ["/web_client/docker_start.sh"]
