# Oil Database Web Client Docker configuration
#
#FROM registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9
FROM node:lts-slim

COPY ./web_client .
COPY ./docker/config/client/ /web_client/configs/
RUN npm install -g ember-cli npm@latest
RUN cd web_client && \
		npm ci && \
		ember build --environment ${BUILD_ENV:-development}

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=0 /web_client/dist/ .
COPY ./docker/config/client/nginx.conf /etc/nginx/conf.d/default.conf