services:
  proxy:
    image: ${SIDECAR_TRAEFIK_IMAGE}
    container_name: traefik
    restart: unless-stopped
    command:
      - '--providers.docker=true' # Discover containers through the Docker provider.
      - '--providers.docker.exposedbydefault=false' # Only expose containers you explicitly label.
      - '--entrypoints.web.address=:80' # Listen on port 80 for unencrypted HTTP.
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      # Automatically redirect HTTP requests (port 80) to HTTPS (port 443).

      - '--entrypoints.websecure.address=:443' # Listen on port 443 for secure HTTPS traffic.
      - '--entrypoints.websecure.http.tls=true' # Enforce TLS for the 'websecure' entrypoint.
      - '--providers.file.directory=/etc/traefik/dynamic/'
      # Load additional Traefik configs from the /etc/traefik/dynamic directory (built into the image).

      - '--log.level=DEBUG' # Enable detailed logs. Useful for troubleshooting.
    ports:
      - '80:80' # Map host port 80 to container port 80 for HTTP (redirecting to HTTPS).
      - '443:443' # Map host port 443 to container port 443 for secure traffic.
    networks:
      - application
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the Docker socket (read-only) so Traefik can see other containers.
    depends_on:
      - client
      - api

  client:
    image: ${CLIENT_IMAGE}
    depends_on:
      - api
    expose:
      - 4200
    restart: on-failure
    networks:
      - application
    labels:
      traefik.enable: 'true' # Enable Traefik for this service.
      traefik.http.routers.client.rule: 'Host(`adios-edit.orr.noaa.gov`)' # Route traffic to this service based on the host.
      traefik.http.routers.client.entrypoints: 'websecure' # Use the secure entrypoint.
      traefik.http.routers.client.service: client
      traefik.http.services.client.loadbalancer.server.port: '4200' # Forward requests to port 4200 in the container.
      traefik.http.services.client.loadbalancer.server.scheme: http

  api:
    image: ${API_IMAGE}
    depends_on:
      - mongodb
    volumes:
      - ../noaa-oil-data:/noaa-oil-data:ro
    expose:
      - 9898
    restart: on-failure
    networks:
      - application
    labels:
      traefik.enable: 'true' # Enable Traefik for this service.
      traefik.http.routers.api.rule: 'Host(`adios-edit.orr.noaa.gov`) &&
        PathPrefix(`/api`)' # Route traffic to this service based on the host.
      traefik.http.routers.api.entrypoints: 'websecure' # Use the secure entrypoint.
      traefik.http.routers.api.service: api
      traefik.http.services.api.loadbalancer.server.port: '9898' # Forward requests to port 4200 in the container.
      traefik.http.services.api.loadbalancer.server.scheme: http

  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    expose:
      - 27017
    networks:
      - application

networks:
  application:
    name: application
    external: false

volumes:
  mongodata:
