- hosts: all
  become: true

  tasks:
    - name: Run Sync script
      command:
        docker exec -i api /bin/bash -c "/web_api/sync_with_production.sh"
      when: "'pub' in ansible_facts['hostname']"
