# Oil Database Web API Docker configuration
#

FROM registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9

ARG KEY_FILE

RUN echo "ip_resolve=4" >> /etc/yum.conf

RUN yum update -y
RUN conda update -y conda \
    && conda update python \
    && conda clean --all

COPY $KEY_FILE /root/.ssh/id_rsa
RUN chmod og-rw /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa

RUN echo "[gitlab.orr.noaa.gov]:9933,[3.133.34.161]:9933 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMgZKGmTe4Qk+PLudgaTbu0R5OzLqqkAxFtp/O+/Aw2YupqtJQb5XDXaPvBtIg2pohmHc66Yjk7HpIoEU/R4+50=" > /root/.ssh/known_hosts
RUN chmod og-rw /root/.ssh/known_hosts

RUN git clone ssh://git@gitlab.orr.noaa.gov:9933/gnome/oil_database/noaa-oil-data.git

COPY ./ /adios-db/
WORKDIR adios-db

# install deps
RUN conda install --file adios_db/conda_requirements.txt --file web_api/conda_requirements.txt \
    && conda clean --all

RUN cd adios_db && pip install -e ./
RUN cd web_api && pip install -e ./

# build docs
RUN cd docs \
    && conda install --file conda_requirements.txt \
    && sphinx-build -a -E -b html source build/html \
    && cp -r build/html ../user_docs \
    && rm -rf build

RUN mkdir /config
RUN cp /adios-db/oildb-deploy/config/stage/web_api/* /config/

EXPOSE 9898
ENTRYPOINT ["/adios-db/web_api/docker_start.sh"]
