#!/usr/bin/env python
import os
import glob
import shutil

from setuptools import setup, find_packages
from distutils.command.clean import clean

# could run setup from anywhere
here = os.path.abspath(os.path.dirname(__file__))
README = open(os.path.join(here, '../README.md')).read()
pkg_name = 'oil_database_api'
pkg_version = '0.0.1'


requires = ['plaster_pastedeploy',
            'pyramid',
            'pyramid_mako',
            'pyramid_debugtoolbar',
            'waitress']

tests_require = ['WebTest >= 1.3.1',  # py3 compat
                 'pytest',
                 'pytest-cov']


def clean_files():
    src = os.path.join(here, pkg_name)
    to_rm = glob.glob(os.path.join(src, r'*.pyc'))
    to_rm.extend([os.path.join(here, '{0}.egg-info'.format(pkg_name)),
                  os.path.join(here, 'build'),
                  os.path.join(here, 'dist')])

    for f in to_rm:
        try:
            if os.path.isdir(f):
                shutil.rmtree(f)
            else:
                os.remove(f)
        except Exception:
            pass

        print "Deleting {0} ..".format(f)


class cleanall(clean):
    description = "cleans files generated by 'develop'"

    def run(self):
        clean.run(self)
        clean_files()


setup(name=pkg_name,
      version=pkg_version,
      description=('{}: {}'.format(pkg_name,
                                   'The NOAA oil library '
                                   'web API server')),
      classifiers=["Programming Language :: Python",
                   "Framework :: Pylons",
                   "Topic :: Internet :: WWW/HTTP",
                   "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
                   ],
      keywords="adios gnome oilspill weathering trajectory modeling",
      author='ADIOS/GNOME team at NOAA ORR',
      author_email='orr.gnome@noaa.gov',
      package_data={'oil_database_api': ['tests/*.py']},
      url='',
      cmdclass={'cleanall': cleanall,
                },
      packages=find_packages(),
      include_package_data=True,
      extras_require={'testing': tests_require,
                      },
      install_requires=requires,
      entry_points={'paste.app_factory': ['main = oil_database_api:main', ],
                    'console_scripts': ['{} = {}:{}'
                                        .format('export_oil_database',
                                                'oil_database_api.scripts.reports',
                                                'export'),
                                        '{} = {}:{}'
                                        .format('audit_oil_database',
                                                'oil_database_api.scripts.reports',
                                                'audit'),
                                        '{} = {}:{}'
                                        .format('audit_oil_cuts',
                                                'oil_database_api.scripts.reports',
                                                'audit_cuts'),
                                        '{} = {}:{}'
                                        .format('plot_oil_viscosity',
                                                'oil_database_api.scripts.plot_oil_viscosity',
                                                'main'),
                                        ],
                    },
      zip_safe=False,
      )
