#!/usr/bin/env python
import os
import glob
import shutil
from pathlib import Path

from setuptools import setup, find_packages
from distutils.command.clean import clean


def get_version(pkg_name):
    """
    Reads the version string from the package __init__ and returns it
    """
    with open(os.path.join(pkg_name, "__init__.py")) as init_file:
        for line in init_file:
            parts = line.strip().partition("=")
            if parts[0].strip() == "__version__":
                return parts[2].strip().strip("'").strip('"')
    return None

pkg_name = 'adios_db_api'

# could run setup from anywhere
here = Path(__file__).parent
README = open(here / '../README.md').read()
pkg_version = get_version(pkg_name)


requires = ['pyramid',
            'pyramid_debugtoolbar',
            'waitress']

tests_require = ['WebTest >= 1.3.1',
                 'pytest',
                 'pytest-cov']


def clean_files():
    src = here / pkg_name
    to_rm = list(src.rglob('__pycache__'))
    to_rm.extend([here / f'{pkg_name}.egg-info',
                  here / 'build',
                  here / 'dist'])

    for f in to_rm:
        try:
            if f.is_dir:
                shutil.rmtree(f)
            else:
                os.remove(f)
        except Exception:
            pass

        print(f'Deleting {f} ..')


class cleanall(clean):
    description = 'cleans files generated by "develop"'

    def run(self):
        clean.run(self)
        clean_files()


setup(name=pkg_name,
      version=pkg_version,
      description=('{}: {}'.format(pkg_name,
                                   'The NOAA ADIOS Database '
                                   'web API server')),
      classifiers=['Programming Language :: Python',
                   'Framework :: Pyramid',
                   'Topic :: Internet :: WWW/HTTP',
                   'Topic :: Internet :: WWW/HTTP :: WSGI :: Application'
                   ],
      keywords='adios gnome oilspill weathering trajectory modeling',
      author='GNOME team at NOAA ORR',
      author_email='orr.gnome@noaa.gov',
      url='https://response.restoration.noaa.gov/oil-and-chemical-spills/oil-spills/response-tools/gnome-suite-oil-spill-modeling.html',
      cmdclass={'cleanall': cleanall,
                },
      packages=find_packages(),
      # include_package_data=True,
      extras_require={'testing': tests_require,
                      },
      install_requires=requires,
      entry_points={'paste.app_factory': ['main = adios_db_api:main', ],
                    'console_scripts': ['{} = {}:{}'
                                        .format('export_adios_db',
                                                'adios_db_api.scripts.reports',
                                                'export'),
                                        '{} = {}:{}'
                                        .format('audit_adios_db',
                                                'adios_db_api.scripts.reports',
                                                'audit'),
                                        '{} = {}:{}'
                                        .format('audit_oil_cuts',
                                                'adios_db_api.scripts.reports',
                                                'audit_cuts'),
                                        # '{} = {}:{}'
                                        # .format('plot_oil_viscosity',
                                        #         'adios_db_api.scripts.plot_oil_viscosity',
                                        #         'main'),
                                        ],
                    },
      zip_safe=False,
      )

