## Nginx Configuration: Adios Database Public Ember Client Server
##
## This configuration is intended to work inside the public facing read-only
## Docker container
user www-data www-data;

events {
    worker_connections 4096;
}

http {
    server {
        listen 80;
        server_name adios.orr.noaa.gov adios-edit.orr.noaa.gov;
        location /about {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /qa-status {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /contact {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /disclaimer {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /privacy {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /configs {
            include /etc/nginx/mime.types;
            root /adios_client/;
        }
        location /oils {
            alias /adios_client/;
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location / {
            include /etc/nginx/mime.types;
            root /adios_client/;
        }
    }
}
