user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log debug;
pid /run/nginx.pid;


events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" "$realpath_root"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    #tcp_nopush     on;

    keepalive_timeout 65;

    gzip on;

    server {
        listen 80;
        root /etc/nginx/html;
        server_name adios.orr.noaa.gov adios-edit.orr.noaa.gov;
        index index.html;
        autoindex on;
        location / {
            try_files $uri $uri/ index.html /index.html =404;
        }
    }
}


## Nginx Configuration: Adios Database Public Ember Client Server
##
## This configuration is intended to work inside the public facing read-only
## Docker container
# events {
#     worker_connections 4096;
# }
# http {
#     server {
#         listen 80;
#         root /etc/nginx/html;
#         server_name adios.orr.noaa.gov adios-edit.orr.noaa.gov;
#         index index.html;
#         autoindex on;
#         try_files $uri $uri/ index.html =404;
# location /about {
#     try_files $uri $uri/ index.html =404;
# }
# location /qa-status {
#     index index.html;
#     try_files $uri $uri/ index.html =404;
# }
# location /contact {
#     index index.html;
#     try_files $uri $uri/ index.html =404;
# }
# location /disclaimer {
#     index index.html;
#     try_files $uri $uri/ index.html =404;
# }
# location /privacy {
#     index index.html;
#     try_files $uri $uri/ index.html =404;
# }
# location /configs {
#     include /etc/nginx/mime.types;
# }
# location /oils {
#     index index.html;
#     try_files $uri $uri/ index.html =404;
# }
# location / {
#     include /etc/nginx/mime.types;
# }
# }
# }