## Nginx Configuration: Adios Database Public Ember Client Server
##
## This configuration is intended to work inside the public facing read-only
## Docker container

events {
    worker_connections 4096;
}

http {
    server {
        listen 80;
        root /etc/nginx/html;
        server_name adios.orr.noaa.gov adios-edit.orr.noaa.gov;
        location /about {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /qa-status {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /contact {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /disclaimer {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /privacy {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location /configs {
            include /etc/nginx/mime.types;
        }
        location /oils {
            index index.html;
            try_files $uri $uri/ index.html =404;
        }
        location / {
            include /etc/nginx/mime.types;
        }
    }
}
