on:
  # Trigger the workflow on push request,
  # but only for the production branch
  push:
    branches:
      - production

jobs:
  build:
    name: Build Sphinx Pages
    runs-on: ubuntu-latest
    steps:
  - name: Modify/add files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test the env that github actions has available
        run: |
          pwd
          ls -la
          ls -la ..
      - name: Build the docs
        run: |
          cd adios_db/cd Documentation/API_docs/
          ./build_api_docs.sh
          make html
          rm -rf ../../../docs/*
          cp -R build/html/ ../../../docs/

          pushd ../../../docs
          git add -A
          git commit -m "update published docs"
          popd

      - name: Push the docs
        run: |
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          git push
