on:
  # Trigger the workflow on push request,
  # but only for the master & develop branch
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build and Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: false
        source_dir: adios_db/Documentation/API_docs/source
        install_extensions: true

